const { getConnection } = require("oracledb")
const { TABLE_PLAYER_ID, TABLE_PLAYER_NAME, TABLE_PLAYER_POSITION, TABLE_PLAYER_PRICE_CURRENT, TABLE_PLAYER_AVAILIBILITY_STATUS, TABLE_PLAYER_CLUB, TABLE_PLAYER_AVAILIBILITY_PERCENTAGE, TABLE_PLAYER, TABLE_CLUB_NAME, TABLE_CLUB, TABLE_CLUB_SHORT_NAME, TABLE_CLUB_LOGO_URL } = require("./constants")

const GET_ALL_PLAYER_OF_CLUB = `SELECT P.${TABLE_PLAYER_ID}, P.${TABLE_PLAYER_NAME}, P.${TABLE_PLAYER_POSITION}, P.${TABLE_PLAYER_PRICE_CURRENT}, P.${TABLE_PLAYER_AVAILIBILITY_STATUS}, P.${TABLE_PLAYER_AVAILIBILITY_PERCENTAGE}, P.${TABLE_PLAYER_CLUB}, C.${TABLE_CLUB_NAME} "player_club", C.${TABLE_CLUB_LOGO_URL} FROM ${TABLE_PLAYER} P JOIN ${TABLE_CLUB} C ON (${TABLE_PLAYER_CLUB} = C.${TABLE_CLUB_SHORT_NAME}) WHERE ${TABLE_PLAYER_CLUB} = :1`

const getAllPlayers = async (club) => {
    const connection = await getConnection()
    console.log(GET_ALL_PLAYER_OF_CLUB);
    const result = (await connection.execute(GET_ALL_PLAYER_OF_CLUB, [club])).rows
    connection.release()
    return result
}

module.exports = {getAllPlayers}